# server port 번호 설정
server:
  port: 8082

# data base 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_springboot
    password: 1234

  # thymeleaf 캐시 설정
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
#      spring.jpa.hibernate.ddl-auto=create => 프로퍼티즈 파일에서 사용
#      create = 프로젝트를 시작할 때 마다 테이블을 새로 생성
#      update = 기존 테이블 유지, 수정사항 반영

# db query log 관련 설정
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace